### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by walkermr** [protostax/ProtoStaxAG_Arduino_Giga_Display_Demo#1]
When i compile the code i get a compile error.

Compilation error: invalid use of incomplete type 'lv_chart_series_t {aka struct lv_chart_series_t}'

Reports line 187 as the source of the error.   
for( idx=0; idx<PDM_NUMBER_SAMPLES; idx++ )
  {
    pdm_series->y_points[idx] = (lv_coord_t)*(dataPDM+idx);
  }

I have all of the correct Libraries installed.

**Comment by walkermr** [comment]
Seems to be a bug in the LVGL library with 9.2.0
rolling back to 9.1.0 allows the demo to compile and load with no issues.

**Comment by sridharrajagopal** [comment]
@walkermr thanks for opening the issue and also for your followup information!

**Comment by sridharrajagopal** [comment]
I fixed the compile error by not accessing y_points directly from lv_chart_series_t but instead using lv_chart_get_y_array. 

The code then compiles with 9.2, but the display is completely messed up, with it rendered upside down and also double charts. Upon googling further, others have similar complaints with Arduino Giga Display sketches with 9.1 not working with 9.2 

See https://forum.lvgl.io/t/what-has-changed-with-lvl-9-2-my-9-1-arduino-giga-sketches-dont-work-any-longer/17942

I'll continue to track that, and update here when there is a resolution. In the meantime, please use LVGL 9.1 

Thanks,
Sridhar

**Comment by MaffooClock** [comment]
For what it's worth, I just tried this today.  I unwittingly already had v9.2.2 of the LVGL library (before I stumbled across this issue, so I was none the wiser), and I'm happy to report that the demo sketch compiles and runs just fine!

Just out of curiosity, I tried v9.2.1, and it also works.  While I was already in the rabbit hole, I decided to give v9.2.0 spin...
> the display is completely messed up, with it rendered upside down and also double charts

... um, I didn't have any of those problems.

So... not a bug?

**Comment by sridharrajagopal** [comment]
Thanks for your clarifications @MaffooClock .  9.2 compiled for me but the display orientations were messed up - I don't know if other libraries' versions had anything to do with our different results. 

 I'll try it again with the versions of the various libraries bumped up to the latest and check again. I saw your pull request too - the imu.begin() == 1 was again due to an issue with the IMU library version I was using. 

Thanks,
Sridhar

**Comment by sridharrajagopal** [comment]
With LVGL 9.2.2 and 9.3 , I get the issue with messed up orientation and double charts, as I had mentioned previously. See attached photo. @MaffooClock can you please confirm that the demo sketch's UI is as expected?

Thanks,
Sridhar

![Image](https://github.com/user-attachments/assets/c6801eba-f8a2-4c76-934b-085b1e3fadc9)

**Comment by sridharrajagopal** [comment]
This is what it should look like! 

[UI](https://github.com/protostax/ProtoStaxAG_Arduino_Giga_Display_Demo/blob/main/ProtoStaxAG_Arduino_Giga_Display_Demo.jpeg)

**Comment by sridharrajagopal** [comment]
Ok, mystery solved! I was running version 4.1.5 of the Arduino Mbed OS Giga Boards library , and with it, the display was messed up with LVGL != 9.1 

I updated to the latest Arduino Mbed OS Giga Boards library, version 4.3.1 , and the example sketch with LVGL 9.3 works fine. 

I'll update the README to reflect the Arduino Mbed OS Giga Boards library version as well .

Thanks, 
Sridhar

**Comment by sridharrajagopal** [comment]
The updated README and the change to imu.begin (thanks @MaffooClock ) have been checked in. 

https://github.com/protostax/ProtoStaxAG_Arduino_Giga_Display_Demo/commit/aeb6afcc22028598053265e7bd4b1b5a16ec54ff
